apiVersion: batch/v1
kind: Job
metadata:
  name: selenium-test-app
spec:
  template:
    spec:
      imagePullSecrets:
      - name: harborcred     
      containers:
      - name: selenium-test-app
        image: registry.kocsistem.com.tr/devops/selenium:v4
      restartPolicy: Never
  backoffLimit: 4